### HERO SETTINGS
HERO_STARTING_HEALTH = 200
HERO_MAX_HEALTH = 200

### PLAYER SETTINGS
PLAYER_STARTING_GOLD = 0
PLAYER_MAX_GOLD = 50
PLAYER_STARTING_INCOME = 2
PLAYER_MAX_HAND_SIZE = 10
PLAYER_MAX_INCOME = 999999 # maybe idk

# DECK SETTINGS
DECK_STARTING_NUM_CARDS = 45

# ARMY SETTINGS
ARMY_MAX_SIZE = 7

# OVERALL GAME SETTINGS
INCOME_PER_X_ROUNDS = 1 # how much income do we gain whenever it increses
X_ROUNDS = 3 # every X_ROUNDS we gain INCOME_PER_X_ROUNDS gold
