from Card import Ally

deck_list = [
    Ally(name="Bear1", cost=1, attack=1, health=1),
    Ally(name="Bear2", cost=2, attack=2, health=2),
    Ally(name="Bear3", cost=3, attack=3, health=3),
    Ally(name="Bear4", cost=4, attack=4, health=4),
    Ally(name="Bear5", cost=5, attack=5, health=5),
    Ally(name="Bear6", cost=6, attack=6, health=6),
    Ally(name="Bear7", cost=7, attack=7, health=7),
    Ally(name="Bear8", cost=8, attack=8, health=8),
    Ally(name="Bear9", cost=9, attack=9, health=9),
    Ally(name="Bear10", cost=10, attack=10, health=10),
    Ally(name="Bear11", cost=1, attack=1, health=1),
    Ally(name="Bear12", cost=2, attack=2, health=2),
    Ally(name="Bear13", cost=3, attack=3, health=3),
    Ally(name="Bear14", cost=4, attack=4, health=4),
    Ally(name="Bear15", cost=5, attack=5, health=5),
    Ally(name="Bear16", cost=6, attack=6, health=6),
    Ally(name="Bear17", cost=7, attack=7, health=7),
    Ally(name="Bear18", cost=8, attack=8, health=8),
    Ally(name="Bear19", cost=9, attack=9, health=9),
    Ally(name="Bear20", cost=10, attack=10, health=10),
    Ally(name="Bear21", cost=1, attack=1, health=1),
    Ally(name="Bear22", cost=2, attack=2, health=2),
    Ally(name="Bear23", cost=3, attack=3, health=3),
    Ally(name="Bear24", cost=4, attack=4, health=4),
    Ally(name="Bear25", cost=5, attack=5, health=5),
    Ally(name="Bear26", cost=6, attack=6, health=6),
    Ally(name="Bear27", cost=7, attack=7, health=7),
    Ally(name="Bear28", cost=8, attack=8, health=8),
    Ally(name="Bear29", cost=9, attack=9, health=9),
    Ally(name="Bear30", cost=10, attack=10, health=10)
]