import DeckLists.Cards as Cards
from Card import Ally

# TODO this is dumb man... just have a list of the references to the cards you want, and the number of each instances for the cards
# take dumb with a grain of salt, its just that its ugly and seems like there are MUCH cleaner ways to do this
deck_list = [
    Ally(orig=Cards.Castle_Ward),
    Ally(orig=Cards.Castle_Ward),
    # Ally(orig=Cards.Castle_Ward),
    # Ally(orig=Cards.Dire_Wolf),
    # Ally(orig=Cards.Dire_Wolf),
    # Ally(orig=Cards.Dire_Wolf),
    # Ally(orig=Cards.Highwaymans_Ambush),
    # Ally(orig=Cards.Highwaymans_Ambush),
    # Ally(orig=Cards.Highwaymans_Ambush),
    # Ally(orig=Cards.Siege_Engineer),
    # Ally(orig=Cards.Siege_Engineer),
    # Ally(orig=Cards.Siege_Engineer),
    # Ally(orig=Cards.Court_Alchemist),
    # Ally(orig=Cards.Court_Alchemist),
    # Ally(orig=Cards.Court_Alchemist),
    # Ally(orig=Cards.Village_Blacksmith),
    # Ally(orig=Cards.Village_Blacksmith),
    # Ally(orig=Cards.Village_Blacksmith),
    # Ally(orig=Cards.Royal_Falconer),
    # Ally(orig=Cards.Royal_Falconer),
    # Ally(orig=Cards.Royal_Falconer),
    # Ally(orig=Cards.Wandering_Minstrel),
    # Ally(orig=Cards.Wandering_Minstrel),
    # Ally(orig=Cards.Wandering_Minstrel),
    # Ally(orig=Cards.Forest_Guardian),
    # Ally(orig=Cards.Forest_Guardian),
    # Ally(orig=Cards.Forest_Guardian),
    # Ally(orig=Cards.Mercenary_Captain),
    # Ally(orig=Cards.Mercenary_Captain),
    # Ally(orig=Cards.Mercenary_Captain),
    # Ally(orig=Cards.Bow_Marshal),    
    # Ally(orig=Cards.Bow_Marshal),    
    # Ally(orig=Cards.Bow_Marshal),    
    # Ally(orig=Cards.Undead_Creatures),
    # Ally(orig=Cards.Undead_Creatures),
    # Ally(orig=Cards.Undead_Creatures),
    # Ally(orig=Cards.Jousting_Champion),
    # Ally(orig=Cards.Jousting_Champion),
    # Ally(orig=Cards.Jousting_Champion),
    # Ally(orig=Cards.Highland_Scout),
    # Ally(orig=Cards.Highland_Scout),
    # Ally(orig=Cards.Highland_Scout),
    # Ally(orig=Cards.Bandit_Outlaw),
    # Ally(orig=Cards.Bandit_Outlaw),
    # Ally(orig=Cards.Bandit_Outlaw)
]
