from Card import Ally

deck_list = [
    Ally(name="Mother Spider", cost=8, attack=4, health=12, text=       "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Mother Spider", cost=8, attack=4, health=12, text=       "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Dire Wolf", cost=6, attack=8, health=5, text=            "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Dire Wolf", cost=6, attack=8, health=5, text=            "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Alpha Beast", cost=7, attack=6, health=10, text=         "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Alpha Beast", cost=7, attack=6, health=10, text=         "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Protected Cub", cost=1, attack=1, health=4, text=        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Protected Cub", cost=1, attack=1, health=4, text=        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Upset Spirit", cost=4, attack=7, health=2, text=         "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Upset Spirit", cost=4, attack=7, health=2, text=         "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Spider Cart", cost=4, attack=3, health=6, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Spider Cart", cost=4, attack=3, health=6, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Wolf Spirit", cost=2, attack=4, health=1, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Wolf Spirit", cost=2, attack=4, health=1, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Bear Spirit", cost=3, attack=5, health=3, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Bear Spirit", cost=3, attack=5, health=3, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Guard of the Forest", cost=8, attack=4, health=15, text= "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Guard of the Forest", cost=8, attack=4, health=15, text= "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Forest's Spite", cost=7, attack=10, health=5, text=      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Forest's Spite", cost=7, attack=10, health=5, text=      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Spider Giant", cost=12, attack=10, health=15, text=      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Spider Giant", cost=12, attack=10, health=15, text=      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Undead Creatures", cost=5, attack=6, health=6, text=     "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Undead Creatures", cost=5, attack=6, health=6, text=     "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Haunted Soul", cost=5, attack=4, health=7, text=         "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Haunted Soul", cost=5, attack=4, health=7, text=         "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Frost Owl", cost=11, attack=9, health=14, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Frost Owl", cost=11, attack=9, health=14, text=          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Menacing Presence", cost=9, attack=9, health=10, text=   "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam"),
    Ally(name="Menacing Presence", cost=9, attack=9, health=10, text=   "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam")
]