from Card import Ally

deck_list = [
    Ally(name="Wolf1", cost=1, attack=1, health=1),
    Ally(name="Wolf2", cost=2, attack=2, health=2),
    Ally(name="Wolf3", cost=3, attack=3, health=3),
    Ally(name="Wolf4", cost=4, attack=4, health=4),
    Ally(name="Wolf5", cost=5, attack=5, health=5),
    Ally(name="Wolf6", cost=6, attack=6, health=6),
    Ally(name="Wolf7", cost=7, attack=7, health=7),
    Ally(name="Wolf8", cost=8, attack=8, health=8),
    Ally(name="Wolf9", cost=9, attack=9, health=9),
    Ally(name="Wolf10", cost=10, attack=10, health=10),
    Ally(name="Wolf11", cost=1, attack=1, health=1),
    Ally(name="Wolf12", cost=2, attack=2, health=2),
    Ally(name="Wolf13", cost=3, attack=3, health=3),
    Ally(name="Wolf14", cost=4, attack=4, health=4),
    Ally(name="Wolf15", cost=5, attack=5, health=5),
    Ally(name="Wolf16", cost=6, attack=6, health=6),
    Ally(name="Wolf17", cost=7, attack=7, health=7),
    Ally(name="Wolf18", cost=8, attack=8, health=8),
    Ally(name="Wolf19", cost=9, attack=9, health=9),
    Ally(name="Wolf20", cost=10, attack=10, health=10),
    Ally(name="Wolf21", cost=1, attack=1, health=1),
    Ally(name="Wolf22", cost=2, attack=2, health=2),
    Ally(name="Wolf23", cost=3, attack=3, health=3),
    Ally(name="Wolf24", cost=4, attack=4, health=4),
    Ally(name="Wolf25", cost=5, attack=5, health=5),
    Ally(name="Wolf26", cost=6, attack=6, health=6),
    Ally(name="Wolf27", cost=7, attack=7, health=7),
    Ally(name="Wolf28", cost=8, attack=8, health=8),
    Ally(name="Wolf29", cost=9, attack=9, health=9),
    Ally(name="Wolf30", cost=10, attack=10, health=10)
]